### ISSUE TITLE
pushbullet - sharing content (cell - PC)

### ISSUE THREAD

**Issue by talesam** [jorgicio/jorgicio-gentoo#8]
Hello, if you can, could create an ebuild for this app is very cool, take a look! Has packages for some distros, less gentoo!

https://www.pushbullet.com/

**Comment by jorgicio** [comment]
Hi! I tried pushbullet-indicator, but at compile, it has errors at compiling libappindicator. Also, it fits better in Unity and other gtk-based environments. And I use KDE.

Maybe later I try again, if that problem is fixed when compiling libappindicator in a non-Unity environments. (Damn, Cannonical!)

**Comment by jorgicio** [comment]
Ebuild created. Sync and install it.
